name = "khtn7"
type = "javascript" # hoặc "webpack", "rust", tùy theo dự án
account_id = "a59c0991f0b291394bbe2fca8ba2694f"
workers_dev = true
compatibility_date = "2025-10-07"

[build]
command = "npm run build" # nếu bạn có script build
upload_format = "modules" # hoặc "service-worker" nếu bạn dùng file index.js

[site]
bucket = "./public"
entry-point = "workers"
